packages:
  - packages/*
  - apps/*

catalogs:
  svelte:
    "@sveltejs/adapter-static": ^3.0.8
    "@sveltejs/kit": ^2.20.8
    "@sveltejs/vite-plugin-svelte": ^5.0.3
    svelte: ^5.28.2
    svelte-check: ^4.1.7
  typescript:
    typescript: ~5.8.3
  vite:
    vite: ^6.3.5
  tauri:
    "@tauri-apps/api": ^2
    "@tauri-apps/plugin-opener": ^2
    "@tauri-apps/cli": ^2
  tailwind:
    tailwindcss: "^4.1.5"
